services:
  dynfi-manager:
    image: dynfi/dynfi-manager
    container_name: dynfi-manager
    hostname: dynfi-manager
    volumes:
      - ./conf:/data/conf
    ports:
      - '9090:9090'
    depends_on:
      - dfmdb

  dfmdb:
    image: mongo
    container_name: dynfi-manager-mongo-db
    volumes:
      - mongo-db:/data/db
    command: ["mongod"]

volumes:
  mongo-db:
    driver: local
